In [1]:
import torch


In [7]:
data_scaler1 = torch.tensor(12)
print(data_scaler1)
print(data_scaler1.dtype)
print(data_scaler1.shape)
print(data_scaler1.device)

tensor(12)
torch.int64
torch.Size([])
cpu


In [9]:
data_scaler2 = torch.tensor(56.7)
print(data_scaler2)
print(data_scaler2.dtype)
print(data_scaler2.shape)
print(data_scaler2.device)
print(data_scaler2.size())

tensor(56.7000)
torch.float32
torch.Size([])
cpu
torch.Size([])


In [11]:
data_scaler3 = torch.tensor(True)
print(data_scaler3)
print(data_scaler3.dtype)
print(data_scaler3.shape)
print(data_scaler3.device)
print(data_scaler3.size())

tensor(True)
torch.bool
torch.Size([])
cpu
torch.Size([])


In [13]:
data_scaler4 = torch.tensor(12, dtype = torch.float64)
print(data_scaler4)
print(data_scaler4.dtype)
print(data_scaler4.shape)
print(data_scaler4.device)
print(data_scaler4.size())

tensor(12., dtype=torch.float64)
torch.float64
torch.Size([])
cpu
torch.Size([])


In [15]:
data_scaler5 = torch.tensor(12., dtype = torch.float64)
print(data_scaler5)
print(data_scaler5.dtype)
print(data_scaler5.shape)
print(data_scaler5.device)
print(data_scaler5.size())

tensor(12., dtype=torch.float64)
torch.float64
torch.Size([])
cpu
torch.Size([])


In [17]:
data_vector1 = torch.tensor([1, 12, 13, 58, 45])
print(data_vector1)
print(data_vector1.dtype)
print(data_vector1.shape)
print(data_vector1.device)


tensor([ 1, 12, 13, 58, 45])
torch.int64
torch.Size([5])
cpu


In [45]:
 data_mat1 = torch.tensor([
     [1, 12, 13, 58, 45],
     [1, 25, 23, 45, 65],
     [24, 58, 26, 25, 66]   
 ])
print(data_mat1)
print(data_mat1.dtype)
print(data_mat1.shape[1])
print(data_mat1.device)
print(data_mat1.size())

tensor([[ 1, 12, 13, 58, 45],
        [ 1, 25, 23, 45, 65],
        [24, 58, 26, 25, 66]])
torch.int64
5
cpu
torch.Size([3, 5])


In [41]:
 data_tens1 = torch.tensor([
     [[1, 12, 13, 58, 45],
     [1, 25, 23, 45, 65],
     [24, 58, 26, 25, 66]],
     [[1, 12, 13, 58, 45],
     [1, 25, 23, 45, 65],
     [24, 58, 26, 25, 66]]
     
 ])
print(data_tens1)
print(data_tens1.dtype)
print(data_tens1.shape[2])
print(data_tens1.device)
print(data_tens1.size())

tensor([[[ 1, 12, 13, 58, 45],
         [ 1, 25, 23, 45, 65],
         [24, 58, 26, 25, 66]],

        [[ 1, 12, 13, 58, 45],
         [ 1, 25, 23, 45, 65],
         [24, 58, 26, 25, 66]]])
torch.int64
5
cpu
torch.Size([2, 3, 5])
