### Reshape 

In [1]:
import torch
import numpy as np
from matplotlib import pyplot as plt

#### Vector

In [10]:
vector_data = torch.randint(1,12,(30,))
print(vector_data )
print(vector_data.shape)
print(vector_data.reshape(2,5,3))
print(vector_data.reshape(2,15))
print(vector_data.reshape(1,3,5,2))

tensor([ 9,  4,  1, 10,  6,  7,  8, 11,  5,  7,  1,  3,  3,  2, 10,  6, 11,  3,
         4,  7,  6,  8,  5,  7,  9,  7,  4,  9,  7, 11])
torch.Size([30])
tensor([[[ 9,  4,  1],
         [10,  6,  7],
         [ 8, 11,  5],
         [ 7,  1,  3],
         [ 3,  2, 10]],

        [[ 6, 11,  3],
         [ 4,  7,  6],
         [ 8,  5,  7],
         [ 9,  7,  4],
         [ 9,  7, 11]]])
tensor([[ 9,  4,  1, 10,  6,  7,  8, 11,  5,  7,  1,  3,  3,  2, 10],
        [ 6, 11,  3,  4,  7,  6,  8,  5,  7,  9,  7,  4,  9,  7, 11]])
tensor([[[[ 9,  4],
          [ 1, 10],
          [ 6,  7],
          [ 8, 11],
          [ 5,  7]],

         [[ 1,  3],
          [ 3,  2],
          [10,  6],
          [11,  3],
          [ 4,  7]],

         [[ 6,  8],
          [ 5,  7],
          [ 9,  7],
          [ 4,  9],
          [ 7, 11]]]])


###### unsqueeze

In [11]:
vector_data1 = torch.randint(1,21,(8,))
print(f"vector_data1.shape : {vector_data1.shape}")
print(f"vector_data1 : {vector_data1}")
vector_data2 = vector_data1.unsqueeze(0)#سطری
print(f"vector_data2.shape : {vector_data2.shape}")
print(f"vector_data2 : {vector_data2}")

vector_data1.shape : torch.Size([8])
vector_data1 : tensor([11, 16, 18,  6, 18, 17, 14, 20])
vector_data2.shape : torch.Size([1, 8])
vector_data2 : tensor([[11, 16, 18,  6, 18, 17, 14, 20]])


In [13]:
vector_data1 = torch.randint(1,21,(8,))
print(f"vector_data1.shape : {vector_data1.shape}")
print(f"vector_data1 : {vector_data1}")
vector_data3 = vector_data1.unsqueeze(1)#ستونی
print(f"vector_data3.shape : {vector_data3.shape}")
print(f"vector_data3 :\n {vector_data3}")

vector_data1.shape : torch.Size([8])
vector_data1 : tensor([11,  8, 12,  1,  6, 10, 19,  6])
vector_data3.shape : torch.Size([8, 1])
vector_data3 :
 tensor([[11],
        [ 8],
        [12],
        [ 1],
        [ 6],
        [10],
        [19],
        [ 6]])


#### Mat

In [16]:
mat_data1 = torch.randint(1,21,(3,5))
print(f"mat_data1.shape : {mat_data1.shape}")
print(f"mat_data1.: \n{mat_data1}")
###unsqueeze
mat_data2 = mat_data1.unsqueeze(0)
mat_data3 = mat_data1.unsqueeze(1)
mat_data4 = mat_data1.unsqueeze(2)
print(f"mat_data.shape : {mat_data2.shape},\n\n,{mat_data3.shape},\n\n,{mat_data4.shape}")
print(f"mat_data : \n{mat_data2},\n\n,{mat_data3},\n\n,{mat_data4}")

mat_data1.shape : torch.Size([3, 5])
mat_data1.: 
tensor([[19, 19,  9, 15, 19],
        [15,  7,  9, 15, 10],
        [18, 14, 19,  2,  8]])
mat_data.shape : torch.Size([1, 3, 5]),

,torch.Size([3, 1, 5]),

,torch.Size([3, 5, 1])
mat_data : 
tensor([[[19, 19,  9, 15, 19],
         [15,  7,  9, 15, 10],
         [18, 14, 19,  2,  8]]]),

,tensor([[[19, 19,  9, 15, 19]],

        [[15,  7,  9, 15, 10]],

        [[18, 14, 19,  2,  8]]]),

,tensor([[[19],
         [19],
         [ 9],
         [15],
         [19]],

        [[15],
         [ 7],
         [ 9],
         [15],
         [10]],

        [[18],
         [14],
         [19],
         [ 2],
         [ 8]]])


##### Squeeze

In [17]:
tens_data1 = torch.randint(1,21,(1,3,1,1,5))
tens_data2 = tens_data1.squeeze(0)
tens_data3 = tens_data2.squeeze(1)
tens_data4 = tens_data3.squeeze(1)
tens_data5 = tens_data4.reshape(15,)
print(f"""mat_data2.shape : {tens_data1.shape},\n\n,{tens_data2.shape},\n\n,
{tens_data3.shape},\n\n,{tens_data4.shape},,\n\n,{tens_data5.shape}""")
print(f"mat_data : {tens_data1},\n\n,{tens_data2},\n\n,{tens_data3},\n\n,{tens_data4},,\n\n,{tens_data5}")


mat_data2.shape : torch.Size([1, 3, 1, 1, 5]),

,torch.Size([3, 1, 1, 5]),

,
torch.Size([3, 1, 5]),

,torch.Size([3, 5]),,

,torch.Size([15])
mat_data : tensor([[[[[ 4, 16,  8, 15, 12]]],


         [[[13,  9, 19,  7, 18]]],


         [[[17, 13, 11, 17, 15]]]]]),

,tensor([[[[ 4, 16,  8, 15, 12]]],


        [[[13,  9, 19,  7, 18]]],


        [[[17, 13, 11, 17, 15]]]]),

,tensor([[[ 4, 16,  8, 15, 12]],

        [[13,  9, 19,  7, 18]],

        [[17, 13, 11, 17, 15]]]),

,tensor([[ 4, 16,  8, 15, 12],
        [13,  9, 19,  7, 18],
        [17, 13, 11, 17, 15]]),,

,tensor([ 4, 16,  8, 15, 12, 13,  9, 19,  7, 18, 17, 13, 11, 17, 15])


## Numpy and Pytorch

In [18]:
nArray=np.array([12,34,546,6,5,76.34,789])
print(f" nArray.shape : { nArray.shape},\n")
print(f" nArray : { nArray},\n")
print(f" nArray.dtype : { nArray.dtype},\n")
print(100*"_")
tens=torch.tensor([12,34,546,6,5,76.34,789])
print(f" tens.shape : { tens.shape}")
print(f" tens : {tens}")
print(f" tens.dtype : {tens.dtype}")
print(100*"_")
tens1=torch.tensor(nArray)
print(f" tens1.shape : { tens1.shape},\n")
print(f" tens1 : {tens1},\n")
print(f" tens1.dtype : {tens1.dtype},\n")
print(100*"_")
tens2=torch.tensor(nArray,dtype=torch.float32)
print(f" tens2.shape : { tens2.shape},\n")
print(f" tens2 : {tens2},\n")
print(f" tens2.dtype : {tens2.dtype},\n")

 nArray.shape : (7,),

 nArray : [ 12.    34.   546.     6.     5.    76.34 789.  ],

 nArray.dtype : float64,

____________________________________________________________________________________________________
 tens.shape : torch.Size([7])
 tens : tensor([ 12.0000,  34.0000, 546.0000,   6.0000,   5.0000,  76.3400, 789.0000])
 tens.dtype : torch.float32
____________________________________________________________________________________________________
 tens1.shape : torch.Size([7]),

 tens1 : tensor([ 12.0000,  34.0000, 546.0000,   6.0000,   5.0000,  76.3400, 789.0000],
       dtype=torch.float64),

 tens1.dtype : torch.float64,

____________________________________________________________________________________________________
 tens2.shape : torch.Size([7]),

 tens2 : tensor([ 12.0000,  34.0000, 546.0000,   6.0000,   5.0000,  76.3400, 789.0000]),

 tens2.dtype : torch.float32,

