### Replace tensor data value

In [1]:
import torch
import numpy as np
from matplotlib import pyplot as plt

In [ ]:
data=torch.randint(1,21,(5,5))#ماتریس 5*5 بین 1تا 20
print(data)
print(data.zero_())
print(data.fill_(1))
data=torch.eye(data.shape[1])
print(data)
z=torch.zeros_like(data)
print(z)

In [14]:
data=torch.randint(1,21,(5,5))#ماتریس 5*5 بین 1تا 20
print(data)
z=torch.zeros_like(data)
print(z)

tensor([[12, 10,  5, 10, 18],
        [17,  3, 16, 20, 20],
        [11,  6,  8, 19,  6],
        [ 9, 12, 18,  5, 12],
        [ 3, 13,  6, 20, 19]])
tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])


### Pytorch Operation

In [18]:
V1=torch.randint(1,21,(8,))
V2=torch.randint(1,21,(8,))
V3=torch.randint(1,21,(10,))
print(V1)
print(V2)
print(V3)
print(100*"=")
print(f"V1 + V2 ==>\n {V1 + V2}")
# print(f"V1 + V2 ==>\n {V1 + V3}")
print(f"V1 - V2 ==>\n {V1 - V2}")
print(f"V1 * V2 ==>\n {V1 * V2}")
print(f"V1 / V2 ==>\n {V1 / V2}")


tensor([13, 11,  8, 20,  4, 18,  4, 14])
tensor([17, 15, 14, 20, 16, 16, 17, 18])
tensor([11, 13, 12, 19, 18,  6,  1, 12,  2, 15])
V1 + V2 ==>
 tensor([30, 26, 22, 40, 20, 34, 21, 32])
V1 - V2 ==>
 tensor([ -4,  -4,  -6,   0, -12,   2, -13,  -4])
V1 * V2 ==>
 tensor([221, 165, 112, 400,  64, 288,  68, 252])
V1 / V2 ==>
 tensor([0.7647, 0.7333, 0.5714, 1.0000, 0.2500, 1.1250, 0.2353, 0.7778])


In [21]:
mat1=torch.randint(1,21,(3,4))
mat2=torch.randint(1,21,(3,4))
mat3=torch.randint(1,21,(4,7))
# print(f"mat1 + mat2 ==>\n {mat1 + mat2}")
# print(100*"_")
# print(f"mat1 - mat2 ==>\n {mat1 - mat2}")
# print(100*"_")
# print(f"mat1 * mat2 ==>\n {mat1 * mat2}")
# print(100*"_")
# print(f"mat1 / mat2 ==>\n {mat1 / mat2}")
# print(100*"_")
print(f"mat1 @ mat2 ==>\n {mat1 @ mat3}")
# print(100*"_")
# print(f"mat1 * mat3 ==>\n {mat1 * mat3}")
print(f"mat1 * mat2 ==>\n {torch.matmul(mat1 , mat3)}")# ضرب ماتریسی

mat1 @ mat2 ==>
 tensor([[174, 421, 345, 305, 499, 374, 219],
        [326, 729, 702, 501, 872, 670, 323],
        [401, 678, 548, 571, 907, 762, 474]])
mat1 * mat2 ==>
 tensor([[174, 421, 345, 305, 499, 374, 219],
        [326, 729, 702, 501, 872, 670, 323],
        [401, 678, 548, 571, 907, 762, 474]])


### Tensor Indexing

In [23]:
torch.manual_seed(42)
vector_data=torch.randint(1,21,(3,6))
print(vector_data)
print(vector_data[0,1])
print(vector_data[-1,1])
print(vector_data[-1,-1])
print(vector_data[2])


tensor([[ 3,  8, 17, 15,  7, 16],
        [ 1,  5, 11, 14, 19, 15],
        [11, 15, 12, 13, 16, 16]])
tensor(8)
tensor(15)
tensor(16)
tensor([11, 15, 12, 13, 16, 16])


### Tensor slicing

In [30]:
vector_data=torch.randint(1,21,(10,))
print(vector_data)
# print(vector_data[2:6])
# print(vector_data[:6])
# print(vector_data[2:])
# print(vector_data[:])
# print(vector_data[:-1])
print(vector_data[: :2])

tensor([19, 12, 15, 12, 17,  4,  3, 11, 10,  9])
tensor([19, 15, 17,  3, 10])


In [40]:
# mat_data=torch.randint(1,21,(7,8))
# print(mat_data)
# # print(mat_data[2:5,1:3])
# # print("\n")
# # print(mat_data[ : ,1:3])
# # print("\n")
# print(mat_data[2:5, : ])
# print("\n")
# print(mat_data[ :5,4: ])
# print("\n")
# print(mat_data[ : , : ])
# print("\n")
mat_data=torch.randint(1,21,(3,5,8))
print(mat_data)
print(100*"=")
# print(mat_data[1:2, :4,2: ])
# print("\n")
# print(mat_data[2])
# print("\n")
# print(mat_data[...])
# print("\n")
# print(mat_data[...,2])
# print("\n")
print(mat_data[...,1,2])

tensor([[[10,  3,  1,  5, 19,  6,  6,  6],
         [ 4, 17, 13,  1, 20,  1,  4, 14],
         [ 3, 13,  1, 18, 11,  8,  3, 18],
         [14,  3, 12,  4, 13,  8, 15,  2],
         [13,  9,  6,  8, 14,  4,  6,  7]],

        [[20,  3, 13, 10, 13,  5, 13,  1],
         [ 6, 13, 18, 10,  7, 12, 20, 18],
         [15, 14, 10, 18, 11, 12,  7,  1],
         [15, 15,  3, 19, 16,  1,  4,  8],
         [ 3, 10, 10, 16,  4, 19,  4,  3]],

        [[18, 10,  9,  2, 20, 18, 15,  2],
         [ 1,  6, 15, 19, 20, 14,  3, 13],
         [ 8, 13, 18, 14, 14, 16,  3, 12],
         [13,  8, 13, 20, 19, 13, 14, 14],
         [16, 14,  1,  6, 15, 15, 16,  5]]])
tensor([13, 18, 15])
